# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true //v3.0 Error occurs

# Setup
title:               lynring24
tagline:             'blog'
description:         '햇병아리가 멋모르고 운영하는 블로그'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              lynring24
  url:               https://twitter.com/mdo
  email:            lync2846@gmail.com

# Custom vars
version:             1.0.0

# Custom Highlighter
highlighter:         rouge

#encoding
encoding: utf-8

#Gems
plugins: [jekyll-paginate]
